### ISSUE TITLE
Brain Jerky bypassing ration control

### ISSUE THREAD

**Issue by anion155** [progwml6/HungerOverhaul#102]
Brain Jerky (from I believe Witching Gadgets) shows +0.5 hunger in tooltip, but when eaten it gives +3 hunger, thaumcraft research points, and it isn't shows in journal, witch means I can eat it infinitly without debuffs. I think this behavior given by Agrarian Skies 2 modpack support mods.

**Comment by squeek502** [comment]
That mod will have to make sure their food integrates with AppleCore. See: https://github.com/squeek502/AppleCore/wiki/Integrating-food-items-with-AppleCore
