### ISSUE TITLE
Tons of NullPointerException

### ISSUE THREAD

**Issue by Adaptivity** [progwml6/HungerOverhaul#103]
When starting MC the log getting spammed by NullPointerException. Also, some NullPointerException refers to SpiceOfLife.

Verison info:
Forge 1492
HungerOverhaul-1.7.10-1.0.0.jenkins77
SpiceOfLife-mc1.7.10-1.2.4
AppleCore-mc1.7.10-1.1.0
CodeChickenCore-1.7.10-1.0.7.47-universal
NotEnoughItems-1.7.10-1.0.5.118-universal
Log: http://pastebin.com/dYwjEYwy

**Comment by squeek502** [comment]
Seems like the events might be getting fired with a null player. Is this new NEI behavior? That doesn't seem right.

**Comment by squeek502** [comment]
To clarify, are these errors when Minecraft is first loading or when you are entering a world?

**Comment by Adaptivity** [comment]
This appeared when I left the world. So far I can't reproduce this but this still can be an issue (maybe this happens random). I still have .log file that is 11mb size.

**Comment by squeek502** [comment]
Crazy. Sounds like it'd be an NEI bug, though. That event probably shouldn't be fired with a null EntityPlayer, and it seems reasonable for mods to assume that the player is not null.

**Comment by Adaptivity** [comment]
Already reported to NEI #233. However, I didn't experienced any lag. But yeah, NEI bug
