### ISSUE TITLE
regrowthMultiplier config options don't allow decimals

### ISSUE THREAD

**Issue by victicdin** [progwml6/HungerOverhaul#110]
After setting cropRegrowthMultiplier to 2.8, it was overwritten with the default after launching minecraft. If I hadn't been configuring my pack inside of a git repo I wouldn't have noticed it.

[Gist](https://gist.github.com/victicdin/c00dba81fb318a9f13bc) for bash log from my git repo. No real way that I know of to collect more evidence. Happens with HO and Pam installed alone, overwrite occurs during initialization phase 1 of forge's loading thing, I assume during HO's initialization. Using HungerOverhaul-1.7.10-1.0.0 and Pam's HarvestCraft 1.7.10j, Applecore 1.1.0.

**Comment by squeek502** [comment]
All the regrowth modifier options only take integers. That's what's causing this.

Leaving this open because it'd be good to change them to use floats if possible.
