### ISSUE TITLE
This mod is incompatible with the latest Harvestcraft build

### ISSUE THREAD

**Issue by Sunconure11** [progwml6/HungerOverhaul#111]
http://pastebin.com/1fm1WnL8

The dev of Harvestcraft merged a bunch of their old mods together it seems.

**Comment by Haggle1996** [comment]
Experiencing this as well.

http://pastebin.com/BQrutjYY

**Comment by Haggle1996** [comment]
@Sunconure11  There's more than one 'latest version' of HarvestCraft...make sure you've downloaded the one with this MD5:  ad98a2681be2073a3cc0429fcc5cbe07

It's loading for me correctly, now that I've got the fixed 1.7.10La HarvestCraft.

**Comment by squeek502** [comment]
Looks like that was a mistake. [Redownload HarvestCraft 1.7.10La.](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294413-pams-mods-nov-27th-2015-1-7-10la-the-missing-link?comment=2167)
