### ISSUE TITLE
latest dev

### ISSUE THREAD

**Issue by SvEgiiVEteR** [progwml6/HungerOverhaul#115]
HungerOverhaul-1.7.10-1.0.0.jenkins86.jar
AppleCore-mc1.7.10-1.2.1+120.4eb8b.jar
after updating my old world(SSP) crash.
http://hastebin.com/afaduwicav.md
and log
https://github.com/SvEgiiVEteR/ModPackSV/blob/master/fml-client-3.log

downgrading AppleCore-mc1.7.10-1.1.0.jar yet working

**Comment by squeek502** [comment]
AppleCore crash. See https://github.com/squeek502/AppleCore/issues/36
