### ISSUE TITLE
Crops grow like hell

### ISSUE THREAD

**Issue by DcNdrew** [progwml6/HungerOverhaul#118]
Hey!
I use Agricraft, Hunger Overhaul, Harder Wildlife and Plant Mega Pack together.
Vanilla crops are okay, but Agricraft crops and PMP plants grow to mature in a day.
Do you know this issue?

Which log do you need?

**Comment by PitchBright** [comment]
Do the grow like hell, when you remove Hunger Overhaul?

**Comment by DcNdrew** [comment]
They do.

**Comment by PitchBright** [comment]
Then it's not a Hunger Overhaul issue then?

**Comment by DcNdrew** [comment]
Give me a sec, I was too fast.

The harvested crop is not the same mature like the just planted. I'm waiting, but it doesn't look like they want to grow fast. Neither the PMP plants.

**Comment by DcNdrew** [comment]
This isn't. Thanks!

**Comment by PitchBright** [comment]
You're welcome!
Please close the issue here, for the devs.
