### ISSUE TITLE
Certain commits not making it into releases

### ISSUE THREAD

**Issue by mathwizi2005** [progwml6/HungerOverhaul#122]
I have been noticing that a commit or two either haven't been making it to releases or being overwritten before a release. Of note that I have found, [this commit](https://github.com/progwml6/HungerOverhaul/commit/2f26ac07d2d09359a7dce53b67f64f5df78d0f5c#diff-360ea69ef36b91e654c6e716776cd5d2) was not pushed to release v1.0 for 1.7.10 on May 10th of this year.

[This pic](http://i.imgur.com/DxXfkbs.png) shows that fix was never applied to the most recent version, 7 months and 5 versions since it was 'fixed' (by date, the fix should have been deployed with Beta 3 on Dec 30th.)

I am honestly hoping this is the only commit that never made it into release but a check to make sure or a full release dump for 1.7.10 would fix any further issue of lost commits.

**Comment by squeek502** [comment]
Yeah, sorry, I've been really neglecting HO. There have actually been [20 commits](https://github.com/progwml6/HungerOverhaul/compare/1.0.0...master) since 1.0.0, and an additional couple that [I haven't quite finished up/tested](https://github.com/progwml6/HungerOverhaul/compare/master...squeek502:master).

Will try to get a new version released soon.

**Comment by mathwizi2005** [comment]
Still doing great work, just don't want those useful commits to fall thru the cracks so no rush.
o wo7

**Comment by progwml6** [comment]
@squeek502 jenkins job should be working again for you to prep the next release

**Comment by progwml6** [comment]
@squeek502 do you want to merge any of those other changes into master before the next release is cut from your fork?

**Comment by squeek502** [comment]
Sure, I'll submit it as a PR if you want to look the changes over first.

**Comment by progwml6** [comment]
@squeek502 feel free to push right to master I'm hoping to wrap up the 1.7.10 stuff soon so that we can get 1.10.2 out

**Comment by progwml6** [comment]
@squeek502 when you have time we can talk on irc about a release plan for this stuff, otherwise feel free to upload to curse yourself

**Comment by mathwizi2005** [comment]
Just bumping this as a general release of current commits is needed
