### ISSUE TITLE
Harvestcraft food chest loot added by Hunger Overhaul has a stack size of 0 (HO 1.7.10-1.0.0)

### ISSUE THREAD

**Issue by theJ8910** [progwml6/HungerOverhaul#126]
Harvestcraft food found in loot chests often has a stack size of 0. Such foods cannot be shift-clicked into / out of inventories, and can instantly disappear when you attempt to eat them without any hunger being restored.

I've observed this problem with the following loot (but suspect it's not limited to just these items): Delighted Meal, Rainbow Curry, Supreme Pizza.

This problem has existed in Hunger Overhaul at least since Minecraft 1.6.4 (since iguana_man was the maintainer), but I'm only reporting the issue now because I suspect I've found the cause.

**Comment by mathwizi2005** [comment]
This particular issue as already been addressed  #122 
Fix is already commited, just not actually released yet. (issue shows the stack size was addressed but not deployed)

**Comment by theJ8910** [comment]
That's great to hear! Thanks for the heads up, and sorry for the duplicate report.
