### ISSUE TITLE
Feature request - config to set food value ourselves

### ISSUE THREAD

**Issue by retep998** [progwml6/HungerOverhaul#127]
It would be really cool if there was a config to let me explicitly choose the food values for any given food item. Such a feature would be immensely useful for modpacks that drastically change recipes and as such the food values of a given food may be quite unbalanced.

If this is implemented, I'd appreciate having it in 1.7.10.

**Comment by squeek502** [comment]
This already exists. See https://github.com/progwml6/HungerOverhaul/wiki#custom-food-values

**Comment by retep998** [comment]
Oh thanks, I didn't think to look in the wiki, and didn't realize this existed yet.
