### ISSUE TITLE
1.10.2-1.1.0 Json file with foods config doesn't take effect

### ISSUE THREAD

**Issue by Bulldog83** [progwml6/HungerOverhaul#132]
Version HungerOverhaul-1.10.2-1.1.0.jenkins111

Json: https://gist.github.com/Bulldog83/ce7baab071d5e5902c1ea3043b0a88d8

**Comment by alexbegt** [comment]
HungerOverhaul-1.10.2-1.1.0.jenkins113 Has this updated fix.
