### ISSUE TITLE
Weighted  Chance For Food To Spawn In Chests is Malfunctioning

### ISSUE THREAD

**Issue by Boolyman** [progwml6/HungerOverhaul#134]
Even using default settings, There is something seriously wrong with the syntax behind the the options to spawn Harvestcraft food into chests for the new 1.10 release.  Dungeon/Mineshaft chests are FILLED to the brim in every single slot with a single piece of Harvestcraft food.  Not only does this prevent other loot from dropping, but there is no reasonable way to fit the dozens of different food items into our inventory.

**Comment by Boolyman** [comment]
Knock Knock...

**Comment by Tellik** [comment]
Boolyman, to give him some credit, he is moving through things, probably as quickly as he can. I noticed a few commits to fix a few bugs that just recently happened, so progress is made. I know some of the troubles from updating a mod from <1.8 to 1.10+, and this is probably going as smoothly as it can.

**Comment by CovertJaguar** [comment]
Can confirm, the value should be a 0.0 to 1.0 float value, not an integer.

**Comment by XxMasonBoyxX** [comment]
> Can confirm, the value should be a 0.0 to 1.0 float value, not an integer.

Hey will you help me with this value im not sure what it should be set to
