### ISSUE TITLE
[1.10.2] Cows milking ignoring the config setting

### ISSUE THREAD

**Issue by JasonMcRay** [progwml6/HungerOverhaul#139]
Little bug I have found, cows can be milked again, ignoring the setting in the hungeroverhaul.cfg file. I have it set to 20 minutes (as per default) but can milk them how many times I want.

Tested in FTB Beyond, where I added couple mods to suit my Let's Play
(List of added mods - Hardcore Darkness, HO, SoL, Realistic Torches and Tough as Nails)

HO: 1.1.0jenkins115

**Comment by alexbegt** [comment]
HungerOverhaul-1.10.2-1.1.0.jenkins116 on curseforge has this fix!
