### ISSUE TITLE
Tooltip problem

### ISSUE THREAD

**Issue by coleweinman** [progwml6/HungerOverhaul#140]
I'm not sure if this is due to HarvestCraft, but the hunger bar tooltip overlaps the "light meal" and "morsel" lore.
![2017-04-24_08 01 50](https://cloud.githubusercontent.com/assets/12768272/25338292/5f8b47f2-28c4-11e7-95c2-07c2f7234ba4.png)

**Comment by ghost** [comment]
What was the solution to this?
