### ISSUE TITLE
[1.10.2] [linux] Config file folder

### ISSUE THREAD

**Issue by bart1ebee** [progwml6/HungerOverhaul#142]
in 1.10.2 on a linux server it creates 2 directories hungeroverhaul and HungerOverhaul. The configs go in the hungeroverhaul directory and they do not load any changes that are made it just overwrites the files.

**Comment by alexbegt** [comment]
I just fixed the duplicate folders with one being Named hungeroverhaul and the other being named HungerOverhaul, but when you say it overrides the files when you reload the server does the timestamp on the file update to a newer time and whatever you just saved resets? I can't recreate that. Mine recreates blankstate and default (which is normal), but not HungerOverhaul.cfg

**Comment by bart1ebee** [comment]
the issue has been fixed thanks for the quick response. sorry for not getting back sooner.
