### ISSUE TITLE
[1.10.2]Tinkerer's Construct Mattock's ignore hoeToolDamageMultiplier

### ISSUE THREAD

**Issue by Mike-T4** [progwml6/HungerOverhaul#143]
Exactly what the title says.
Mattock's from Tinkerer's Construct lose 1 durability when tiling land, regardless of the setting of hoeToolDamageMultiplier.

**Comment by alexbegt** [comment]
Tinker Construct's tools will not follow the hoeToolDamageMultiplier, and I have no control over that as Tinkers has its own special way of damaging the tools.
