### ISSUE TITLE
1.10.2 No display of saturation

### ISSUE THREAD

**Issue by PearlCanopus** [progwml6/HungerOverhaul#149]
I checked that out with only Forge, AppleCore and Hunger Overhauls installed. So no foreign mod influence is possible.

Using AppleSkin I see saturation icons but not for only Hunger Overhaul.

**Comment by squeek502** [comment]
That is something that was part of AppleCore in previous Minecraft versions, but was moved to AppleSkin in 1.10.2+. It was never part of Hunger Overhaul.
