### ISSUE TITLE
1.12.2 

### ISSUE THREAD

**Issue by ghost** [progwml6/HungerOverhaul#154]
Hi, i just wanted to ask if the 1.12.2 branch is working and how i can compile it. When I run gradle build, i get three .jar files and none of these work. If it's not working, how long do you think you need? And if there is plenty of work I would offer my help on updating the mod. But we should contact so you can tell me what needs to be done and what already is. Looking forward to hear from you.
Sorry for posting this here, but there is no messagefunction on github ^^.

**Comment by alexbegt** [comment]
Hi there,

1.12.2 Has been posted to curse, Please open a new issue if you run into any issues!

Thanks,
Alexander (Alexbegt)
