### ISSUE TITLE
[1.12.2] Bonemeal changes don't affect pam's harvestcraft crops

### ISSUE THREAD

**Issue by Insane96** [progwml6/HungerOverhaul#159]

**Comment by alexbegt** [comment]
Which crops do they not affect?

**Comment by Insane96** [comment]
I've only checked for cactus fruit, I'm traveling right now, ASAP, if needed, i'll check other crops

Forgot to mention that I'm using the latest version for MC 1.12.2

**Comment by Insane96** [comment]
Checked most of the seeds and all of them grow with 1-2 bonemeal

**Comment by alexbegt** [comment]
Has been fixed in https://github.com/progwml6/HungerOverhaul/commit/9ba1e0318a143eaea4061bd528989cc111310610
