### ISSUE TITLE
[1.12.2] Harvestcraft Fruit trees drop fruit blocks

### ISSUE THREAD

**Issue by Insane96** [progwml6/HungerOverhaul#163]
https://github.com/MatrexsVigil/harvestcraft/issues/104

![](https://user-images.githubusercontent.com/7185104/34736057-f48cb9d8-f571-11e7-9b49-59d6817e5b00.png)

Both when right clicked and destroyed
  
 Setting _modifyCropsRightClick_ and _modifyCropsBreak_ to _false_ should temporarly fix this

**Comment by alexbegt** [comment]
Has been fixed in https://github.com/progwml6/HungerOverhaul/commit/9ba1e0318a143eaea4061bd528989cc111310610
