### ISSUE TITLE
[1.12.2] You can't plant pam's crops directly

### ISSUE THREAD

**Issue by Insane96** [progwml6/HungerOverhaul#164]
https://github.com/MatrexsVigil/harvestcraft/issues/105

**Comment by alexbegt** [comment]
What do you mean by this?

**Comment by Insane96** [comment]
Without Hunger Overhaul: https://youtu.be/gBEeuNnL_m0
With Hunger Overhaul: https://youtu.be/IyQvTLWmgt0

As you can see, I can't plant the blackberry directly with HO.

**Comment by alexbegt** [comment]
This is actually a config feature, just disable foodsUnplantable: "Makes HarvestCraft foods unplantable, meaning seeds are required to plant crops"

**Comment by Insane96** [comment]
Wow. I'm so blind. I've checked the config like 100 times and didn't find it.
