### ISSUE TITLE
[Suggestion] Add a config to slowdown / disable the fast health regeneration when full hunger and saturation

### ISSUE THREAD

**Issue by Insane96** [progwml6/HungerOverhaul#165]
The one added back in 1.9

**Comment by StoneNation** [comment]
I have also been looking for a way to disable that for a while now.  I know it has been done before but I'm not sure if It was with hunger overhaul or some other mod. It would be great if there was a config for it.

**Comment by paulgb434** [comment]
Mods already exist for that, look at Regen Control and Health and Hunger Tweaks on Curseforge.
