### ISSUE TITLE
crash due to right click using a iron bucket on a pams harvest crops 

### ISSUE THREAD

**Issue by trilexcom** [progwml6/HungerOverhaul#172]
## Version Information
`Minecraft: 1.12.2
`Forge: `2590
`Mantle: `1.12-1.3.1.21
`Natura: `1.12.2-4.3.2.42
Pams HarvestCraft : 1.12.2l
`Apple Core: `AppleCore-mc1.12.2-3.1.0
`Hunger Overhaul: `1.12.2-1.3.0.jenkins139

## Report Information

my client crash when i right on pams Harvestcraft crops 

## Steps to Reproduce

right click using a iron bucket on a pams harvestcraft crop (harvestcraft:pamcranberrycrop)

## Crash Log

https://pastebin.com/5y9ihJUG

## Forge Log

http://www.filedropper.com/logs_23

**Comment by trilexcom** [comment]
now we have a server crash due to this problem https://pastebin.com/PkeR0thm please let me know if i need to contact pam or if this is hungeroverhaul issue 

thanks 

mat

**Comment by trilexcom** [comment]
i am going to delete the config file for hungeroverhaul and harvestcraft and see if it does the job. 

i will post a update on this ticket soon 

mat

**Comment by trilexcom** [comment]
same problem with the new update by the way 

same problem here too https://pastebin.com/0K5xSP33

i tried few troubleshooting steps i reg the config for harvestcraft and tried again it didn't do anything , still the same issue, this is when you right click on the crop to harvest, if you left click on the crop it wont give you anything either

we report this to HarvestCraft too https://github.com/MatrexsVigil/harvestcraft/issues/136

**Comment by alexbegt** [comment]
I have to release a new version of HungerOverhaul before the bug is fixed.
