### ISSUE TITLE
Crash with Harvestcraft 1.12.2 

### ISSUE THREAD

**Issue by ghost** [progwml6/HungerOverhaul#173]
## Version Information
`Minecraft: ` 1.12.2
`Forge: ` 14.23.1.2600
`Mantle: ` Mantle-1.12-1.3.1.21
`Natura: ` natura-1.12.2-4.3.2.42
`Apple Core: ` AppleCore-mc1.12.2-3.1.0
`Hunger Overhaul: ` HungerOverhaul-1.12.2-1.3.0.jenkins139
`Pam's HarvestCraft: ` Pam's+HarvestCraft+1.12.2m

## Report Information

For what I can tell in the crash report it has something to do with the pamcandleberrycrop from harvestcraft, but the crash itself happened randomly when I was crafting some planks in the crafting table.

## Steps to Reproduce

Like I said I was crafting some planks and it happened immediately when I shift clicked the planks to do the crafting, though I doubt it has any relation with the crash.

## Crash Log
 
https://pastebin.com/qUbcuXGY

## Forge Log

https://pastebin.com/Gfk0brhG

I apologize if this is on harvestcraft side I'm not sure since the crash report points to both mods

**Comment by trilexcom** [comment]
you might want to report this to harvestcraft sense we are doing that too, just a fyi https://github.com/MatrexsVigil/harvestcraft/issues/136

**Comment by alexbegt** [comment]
I have to release a new version of HungerOverhaul before the bug is fixed.
