### ISSUE TITLE
Right click crash with pams harvest craft

### ISSUE THREAD

**Issue by errors1** [progwml6/HungerOverhaul#178]
## Version Information
`Minecraft: 1.12.2 `
`Forge: forge1.12.2-14.23.1.2583 `
`Apple Core: AppleCore-mc1.12.2-3.1.0`
`Hunger Overhaul: HungerOverhaul-1.12.2-1.3.0.jenkins139 `
`Pam's Harvest Craft: Pam's+HarvestCraft+1.12.2o`

## Report Information

Right clicking on any Pam's Harvest planted plants regardless of growth stage crashes the game.

## Steps to Reproduce

Load listed mods > Tilled dirt with water next to it > Plant Pam's seed(any kind) >  Right click > crash

## Crash Log

https://pastebin.com/qnMXbvqr

## Forge Log

https://pastebin.com/AnTu64SH

**Comment by alexbegt** [comment]
Please upgrade to HungerOverhaul-1.12.2-1.3.1.jenkins142 and reply back if this error still occurs.

**Comment by errors1** [comment]
The error is gone,  Thanks for the help.
