### ISSUE TITLE
1.12.2 right click harvest with harvestcraft then crash!

### ISSUE THREAD

**Issue by alxcool** [progwml6/HungerOverhaul#181]
## Version Information
`Minecraft: `1.12.2
`Forge: `2603
`Mantle: `21
`Natura: `35
`Apple Core: 3.1`
`Hunger Overhaul: `3.1 or 142

## Report Information
I was searching some vegetable to cook as my hunger was low 2/10. I had 2 lv2 negative effects.
10 am, a plot yard.

## Steps to Reproduce
Harvest a Onion crops with right click (from harvestcraft.)

## Crash Log
(available for 2 weeks)
https://pastebin.com/RcqXYLAv

## Forge Log

You'r Welcome ;)

**Comment by alexbegt** [comment]
Please update your HarvestCraft to the latest version and report back if this still occurs
