### ISSUE TITLE
Game Crash due to hungeroveral api with Biomes of Plenty

### ISSUE THREAD

**Issue by trilexcom** [progwml6/HungerOverhaul#185]
## Version Information
`Minecraft: `1.12.2
`Forge: `2657
`Mantle: `1.3.2.24
`Natura: `4.3.2.42
`Apple Core: `2-3.1.1
`Hunger Overhaul: `1.3.1
`Biomes of Plenty : `7.0.1.2355

## Report Information

game crash with latest version of Biomes of Plenty

## Steps to Reproduce

just install biomes of plenty and hunger overhaul with latest version it crashes 

## Crash Log

https://pastebin.com/pu6dpsbn

## Forge Log

https://github.com/progwml6/HungerOverhaul/files/1911584/fml-client-latest.log

**Comment by Gyromax** [comment]
I have encountered the same Error, with the at least for now latest Versions:

**Version Information**
Minecraft: 1.12.2
Forge: 2666
Mantle: 1.3.2.24
Natura: 4.3.2.42
Apple Core: 3.1.1
Apple Skin: 1.0.9
Hunger Overhaul: 1.3.1
Biomes of Plenty : 7.0.1.2360

**Crash Log**
https://pastebin.com/9DzCWE3Q

**Comment by collwee** [comment]
happen with Biomesoplenty 7.0.1.2355 and up. it seams they removed food items in that version

Crash Log
https://paste.ee/p/NSecY

**Comment by QAngelusQ** [comment]
Same Issue for me as well:

Minecraft: 1.12.2-2655
https://pastebin.com/SvfTBZNZ

**Comment by NanayaQ** [comment]
Confirm crash with BoP

Log
https://pastebin.com/HGz4VKn0
