### ISSUE TITLE
Wood and cobble hoe recipes not disabled by config

### ISSUE THREAD

**Issue by dmz2112** [progwml6/HungerOverhaul#188]
## Version Information
`Minecraft: ` 1.12.2
`Forge: ` 14.23.3.2698
`Mantle: ` N/A
`Natura: ` N/A
`Apple Core: ` 3.1.1
`Hunger Overhaul: ` 1.3.2.jenkins146

## Report Information
Despite the default settings in the config:
```
    # Whether wood and stone hoe recipes are removed [vanilla: false] [default: true]
    B:removeHoeRecipes=true
```
Wood and cobble hoes can be constructed and used.
(For the record, I would probably disable this if it were working; I only noticed the config settings while I was altering other values.)
I'm not using any mods that alter vanilla crafting, so I don't think it is an issue of interference.

## Steps to Reproduce
Construct a vanilla wood or cobble hoe in a vanilla crafting grid
Equip hoe
Right click on grass blocks exposed to water
Right click on grass blocks not exposed to water

**Comment by Insane96** [comment]
This is because the line that should remove the recipes is commented out https://github.com/progwml6/HungerOverhaul/blob/fa31d88454ff236d5b3f23d36a11a80f7d871ff6/src/main/java/iguanaman/hungeroverhaul/library/RecipeRemover.java#L37
