### ISSUE TITLE
Pam's Harvestcraft gooseberry trees drop both ripe crop and unripe tree block upon harvest.

### ISSUE THREAD

**Issue by MoxieGrrl** [progwml6/HungerOverhaul#189]
Minecraft Version: 1.12.2
Applecore Version: 3.1.1
Hunger Overhaul version: 1.3.2
Harvestcraft version: 1.12.2u
Forge version 2702

Before harvesting: fully mature fruit.
![2018-05-23_13 34 24](https://user-images.githubusercontent.com/7219616/40444135-198935e2-5e8e-11e8-85ae-05ea27126107.png)

After harvesting. Both the mature crop item and the immature block drop.
![2018-05-23_13 34 30](https://user-images.githubusercontent.com/7219616/40444155-25762e96-5e8e-11e8-99c9-0a028d756be2.png)

I have more gooseberries now than anyone needs in one lifetime. Send help.

And as far as I can tell, it's only the gooseberries. Plums didn't do this. I figure I'll test all the other fruit trees, but yeah. Config file on this one is as shipped. I changed a few things in my actual play instance so I pulled it out to test.

**Comment by drakray** [comment]
Sorry to hijack this, but [HarvestCraft 1.12.2za](https://minecraft.curseforge.com/projects/pams-harvestcraft/files/2628183) adds new tree, and they have the same issue
