### ISSUE TITLE
Cycle in load order

### ISSUE THREAD

**Issue by VladoCC** [progwml6/HungerOverhaul#190]
I had created mod that uses AppleCore and want to load it after all AppleCore dependant mods.
But your mod wants to load after all other mods. And for this reason forge stops loading.
Can you change this or add additional tag "before" for my mod?

**Comment by VladoCC** [comment]
I can make pull request (with "before" tag) if you want, but I can not check if it fixes my problem or not (theoretically yes) or not, because server with one of your dependencies now offline.

**Comment by VladoCC** [comment]
Yeah, I rechecked everything and my fix is working. Merge pull request please.

**Comment by VladoCC** [comment]
@alexbegt can you help,please?

**Comment by alexbegt** [comment]
Well you said "want to load it after all AppleCore dependent mods", HungerOverhaul needs AppleCore to modify the food values. So shouldn't your mod load after HO?

**Comment by VladoCC** [comment]
Maybe I said something wrong, sorry, English is not my native language. But I am sure that I want to load my mod after HO.

**Comment by alexbegt** [comment]
Okay I merged your pull request, and I am going to close this ticket!

**Comment by VladoCC** [comment]
Thanks, @alexbegt . When this change will be available as jar file?
