### ISSUE TITLE
Crash on Initilialization

### ISSUE THREAD

**Issue by LamePos** [progwml6/HungerOverhaul#209]
Crashes on startup. I know I have a lot of mods that are undoubtedly causing the conflict, I just figured I'd post the logs here anyway.

## Version Information
Minecraft: 1.12.2
Forge: 14.23.5.2768

Crash log >> https://pastebin.com/LrVxAzSQ
Forge log >> https://pastebin.com/S8AiYUUv

EDIT:

Noticed my applecore was out of date, updating did not resolve the issue.

Latest Crash log >> https://pastebin.com/AjDjZbmR

EDIT 2 : Oddly enough, removing natura resolves the issue. Not sure what to say about that. I thought maybe my outdated Mantle CoreMod was causing it, but after updating it the latest version (1.3.3.42) and double-checking that Natura was up to date (4.3.2.66), the game only fully initializes if Natura isn't loaded. I have not tried loading only Natura, Mantle, AppleCore, and Hunger OverHaul,

**Comment by paulgb434** [comment]
Did you disable any of the modules in the NatureModules.cfg file? I think this crash is identical to the one I had with Natura, but it only occurred when one or more of the modules in that file were set to false. When they were all set to "true" as default, no crash occurred.

**Comment by LamePos** [comment]
I'll double check when I get a chance and report back to you.
