### ISSUE TITLE
Incompatibility With Hunger Persistence, disable respawnHungerValue?

### ISSUE THREAD

**Issue by Ethern8ai** [progwml6/HungerOverhaul#212]
## Version Information
`Minecraft: `all
`Forge: `all
`Mantle: `all
`Natura: `not
`Apple Core: `all
`Hunger Overhaul: `all

## Report Information

Great mod! good luck with it all

**Comment by squeek502** [comment]
Some more context: https://minecraft.curseforge.com/projects/hunger-persistence?comment=8

**Comment by progwml6** [comment]
@squeek502 are you able to add this config yourself?

**Comment by squeek502** [comment]
I could, should be pretty simple. Will try to do that in the next few days.

**Comment by Ethern8ai** [comment]
Thanx Squeek502 :) its a good plus to get this two mods fully compatible :D
Good luck with all!
