### ISSUE TITLE
Pixelmon & hunger overhaul mod crash

### ISSUE THREAD

**Issue by rebarakuk** [progwml6/HungerOverhaul#244]
## Version Information
`Minecraft: ` 1.12.2
`Forge: ` 14.23.5.2860
`Mantle: ` 1.3.3.55
`Natura: `
`Apple Core: ` 3.4.0
`Hunger Overhaul: ` 1.3.3.jekins148
`Pixelmon: ` 8.3.6

## Steps to Reproduce

when I touch a pixelmon fruit on pixelmon fruit category of creative mod, it crashes.

## Crash Log

https://gist.github.com/rebarakuk/23749cf4bc7caa8ae1b437975fa58999

**Comment by iomaptob** [comment]
Duplicate of #195 
I wrote the solution in this issue, you can find it in the last comment.
You can also find the workaround on the [Pixelmon wiki](https://pixelmonmod.com/wiki/Incompatibilities%20list) under the _Other conflicts_ section.

**Comment by rebarakuk** [comment]
thx!!
