### ISSUE TITLE
Add a recipe to craft Barley seeds

### ISSUE THREAD

**Issue by p-schneider** [progwml6/HungerOverhaul#39]
I think it would be useful to have a way to get Barley seeds other than punshing grass.
You already added a Recipe to convert Wheat into Seeds so I think something like this should be added to [iguanaman.hungeroverhaul.module.ModuleNatura](https://github.com/progwml6/HungerOverhaul/blob/master/src/main/java/iguanaman/hungeroverhaul/module/ModuleNatura.java#L29):
```java
GameRegistry.addRecipe(
 new ShapelessOreRecipe(
  new ItemStack(NContent.seeds, 1, 0),
  new ItemStack(NContent.plantItem, 1, 0)
)); //1 Barley -> 1 Barley Seeds
```
edit: The main reason for my suggestion is that on left click fully grown barley only drops barley and no barley seeds the same way wheat does. If the barley isn't fully grown it does drop one single barley seed, so there is no way to multiply existing seeds. It seems like cotton has the same *problem* but I didn't test it enough to be sure about it.

**Comment by Parker8283** [comment]
Better late than never :P

Makes sense and seems fair. I say add it.
