### ISSUE TITLE
Crash with .json settings

### ISSUE THREAD

**Issue by MrPotatoGaming** [progwml6/HungerOverhaul#66]
Versions: Forge 1236 & 1277, Apple Core 1.0.2, Hunger Overhaul Beta 4

When having any file in the config folder, the game crashes. Even if it's a copy and pasted .json from the wiki. I have attempted to [use default wiki](http://pastebin.com/r65DDCN9), [remove comments](http://pastebin.com/wW8B0uA8), [strip to a single change](http://pastebin.com/6nMnwm7M), and [remove comments from single](http://pastebin.com/UbbCKCWm). All of which resulted in the same [crash](http://pastebin.com/ks0fEuUU) After that I tried deleting the main config file.

I did check these in a json validator. The only ones it complained about was the commented ones.

**Comment by squeek502** [comment]
Looks like an oversight on my part. You could probably avoid the crash by including all sections in one JSON file (have a foods, foodsBlacklist, dropsBlacklist, and harvestBlacklist section defined).

Will look into it some more and fix it later today.
