### ISSUE TITLE
Stuck in sprint mode hunger drain

### ISSUE THREAD

**Issue by mikebriggs2k** [progwml6/HungerOverhaul#72]
I have been trying to reliably reproduce this, but I have not been able to. On multiple occasions I've gotten "stuck" in sprint mode hunger drain even when I'm not sprinting. If I have enough food to reactivate sprint and stop sprinting it subsides; However, I've noticed it happen most when I was really low on food and couldn't activate sprint again to disable it again. Short of that, logging off and back on work.

I'm running a custom modpack with 60 other mods. I'm currently using Hungeroverhaul-beta-4 along with AppleCore 1.0.2. If you would like the full modlist, let me know.

**Comment by squeek502** [comment]
This would either be a vanilla bug or some other mod's. Neither HO or AppleCore touch sprint exhaustion at all.
