### ISSUE TITLE
server crash - Ticking block entity - mfr harvester involved

### ISSUE THREAD

**Issue by Terpo** [progwml6/HungerOverhaul#76]
I'm updating my modpack and was checking if everything on the map is working.

I teleported to the block and there is only a normal wheat farm. It seems to crash when a crop gets harvested by the mfr harvester.

http://pastebin.com/5QzSdmkx

after a few more tests it seems that there is a problem with my hungeroverhaul food json. If there is no json file, it works :)

here is a link of my food.json
http://pastebin.com/npwqX1Au

**Comment by squeek502** [comment]
Fixed by eae6ce678a00c047b381fbdeb40efb6973647fed

Just FYI, the problem with your json is that you commented out the contents of the objects in foodsBlacklist/dropsBlacklist/harvestBlacklist rather than the objects themselves, so you were adding a blank object to the blacklist.

Compare:
```javascript
"someKey": [
  {
    // empty object
  }
]
```
to:
```javascript
"someKey": [
  // empty list
]
```
