### ISSUE TITLE
Create a 'blank slate' config (config with all HO changes disabled)

### ISSUE THREAD

**Issue by squeek502** [progwml6/HungerOverhaul#78]
This would be good for two reasons:
* It'd be helpful for pack-makers/etc to start from, so that it's easy for them to only enable what they want from HO
* It'd give us a better idea about what HO doesn't provide a config option for. A blank slate *should* be possible, but I really doubt it is right now.

This could just be a wiki page or something, or it could be generated by the mod and written either to something like `config/HungerOverhaul_blankslate.cfg` or `config/HungerOverhaul/blankslate.cfg`

**Comment by Parker8283** [comment]
This seems like a great idea, though I have no clue how you will pull this off cleanly. I would suggest the HO config folder, and migrate the old HungerOverhaul.cfg to the folder and rename main.cfg or something like that.
