### ISSUE TITLE
Make sure *everything* can be disabled through the config

### ISSUE THREAD

**Issue by squeek502** [progwml6/HungerOverhaul#79]
Related to #78, there are some things that are not totally disable-able through the config. Things I'm aware of:

- [x] seedChance
- [x] milkedTimeout (might be fine set at 0, but need to make sure)
- [x] the entire "harvesting" category (modifying crop produce/seed drops)
- [x] lowHealthRegenRateModifier
- [x] Wheat seeds recipe
- [x] Removal of Natura wheat/barley flour recipes/smelting

There are probably others...

**Comment by Razorskills** [comment]
Would it also be possible to separate this config here:
```
    # Slowness effect when health/hunger is low ('addLowStatEffects' must be true)
    B:addLowStatSlowness=true

    # Weakness effect when health/hunger is low ('addLowStatEffects' must be true)
    B:addLowStatWeakness=false
```
for health to be set to false, but hunger to true

**Comment by squeek502** [comment]
Going to consider this done, although it's not totally confirmed; there might still be some lingering things that need config options.
