### ISSUE TITLE
Harvest changes cause Thaumic Tinkerer infused seeds to drop wheat

### ISSUE THREAD

**Issue by belathus** [progwml6/HungerOverhaul#80]
I talk about it a bit with Nekosune below:

https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/671

I disabled Hunger Overhaul and stopped getting wheat, though, it doesn't seem to affect any other drops associated with the infused seeds.

**Comment by Qohelethh** [comment]
I fixed this by blacklisting infused crops from the right click harvest changes.
