### ISSUE TITLE
Config request: More comments on default values

### ISSUE THREAD

**Issue by erima** [progwml6/HungerOverhaul#82]
I make a lot of tweaks to Hunger Overhaul and find the comments on default values - erm - valuable. I'd love to see comments on each setting, with both Hunger Overhaul defaults and Vanilla if applicable. Example:

```
    # Speed up or slow down the rate that hunger drops (set to 0 to disable hunger loss)
    I:hungerLossRatePercentage=30
```

I changed this to 30 and noticed I'm never getting hungry now. I'd like to make it closer to Vanilla than default Hunger Overhaul, but don't know either value.

I must add, kudos to everyone for HO already having terrific config comments.

**Comment by squeek502** [comment]
The default value in the config comments was done by 77026de75cba208255081ed6e664000e0c8559a6. 

The Vanilla value stuff was also done by that commit (see also #78), but the 'blank slate' value won't show in the config comment. I'll add that.
