### ISSUE TITLE
JSON config files have no effect

### ISSUE THREAD

**Issue by Qohelethh** [progwml6/HungerOverhaul#84]
I have been trying to use JSON files to alter HungerOverhaul's default behavior. For example, I'm trying to remove the right click harvest behavior for wheat. 

I tried following the guide, but I can't get anything to work. This probably isn't the right place to ask this question, but I wasn't sure where to ask it.

Here's the JSON file: https://gist.github.com/Qohelethh/beecb7f1bfa7e81c73d3

**Comment by squeek502** [comment]
You have some syntax errors (missing commas), and the optional note means that the key itself is optional, not the value.

Try this:
```javascript
{
    // a list of foods that should not have their food values modified by HO
    // the foods in this list will not have their values changed by HO at all (even if specified in the 'foods' section above)
    "foodsBlacklist": [
        {
            // the name of the item in "mod:name" format
            "name": "TwilightForest:item.hydraChop",
            // [optional] the metadata value of the item (default: wildcard (any metadata))
            "meta": 0
        }
    ],

    // a list of crop blocks that should not have their right-click behavior modified by HO
    "harvestBlacklist": [
        {
            // the name of the block in "mod:name" format
            "name": "minecraft:wheat"
        },
	{
            // the name of the block in "mod:name" format
            "name": "yegamolchattels:flax_plant"
        },
	{
            // the name of the block in "mod:name" format
            "name": "Natura:barleyFood"
        }
    ]
}
```

**Comment by Qohelethh** [comment]
Thank you so much. That works for everything except the Natura barley, so I'm guessing I don't have the right name for it. Any advice on how to find the right name?

**Comment by squeek502** [comment]
No problem. If you have Waila installed, turn on "Show ID:Metadata" in the Waila options (NUMPAD 0 by default).

**Comment by Qohelethh** [comment]
That worked. Thanks for all the hard work on this mod!
