### ISSUE TITLE
Saturation food tooltips do not match actual saturation

### ISSUE THREAD

**Issue by Barhandar** [progwml6/HungerOverhaul#93]
HO 1.0.0, AC 1.1.0.

Presumably related to the "saturation for all food is infinite" bug. AppleCore's tooltip reports some saturation (for example, HC Bacon Mushroom Burger: 8.5 shanks of saturation, 8 shanks of hunger), HO's reports different (respectively, "Unfulfilling"). Growthcraft's drinks have negative saturation and are also "unfulfilling", melon slices, sodas, and a lot of other mod "Snack"-level hunger foods are "Hearty" despite restoring .5-2.5 shanks of saturation, HC's Cherry Cheesecake lacks saturation tooltip (7.5 actual saturation shanks, 6 hunger shanks - also reports as "Feast"), all "Nourishing" foods, to the one, have .5 saturation and .5 hunger shanks, et cetera. 

F3 menu reports expected saturation, for example HC:Roasted Pumpkin Seeds, with 1 shank of hunger and 1.5 of saturation, eaten at 19 hunger value, resulted in 20 hunger and 2.4 saturation despite saying they're "Hearty".

**Comment by squeek502** [comment]
Are you playing on a server? If so, is this reproducable in single player?

**Comment by Barhandar** [comment]
Yes, and yes, singleplayer has identical issue.

**Comment by squeek502** [comment]
Can you post your config and any HO .json files you're using (if any)? Use http://pastebin.com or something similar.

**Comment by squeek502** [comment]
This might actually be down to saturation being a confusing mechanic.

1 saturation bar = 2 saturation. So the 1.5 saturation bars of roasted pumpkin seeds could actually be 2.4 saturation (and it might actually be showing 1.25 saturation bars in the tooltip).

The HO "Feast", "Nourishing", etc tooltips [have some weird logic to them](https://github.com/progwml6/HungerOverhaul/blob/master/src/main/java/iguanaman/hungeroverhaul/util/IguanaEventHook.java#L449-L476).

But, still, post your config + any .json files you're using and I'll be able to take a better look.

**Comment by Barhandar** [comment]
http://pastebin.com/dAe4VPiq

Sure, but in previous versions tooltip worked as expected, with description near-completely matching what AppleCore displayed - e.g. one-shank foods were all "Morsel", there were "Wholesome Feasts", et cetera.

**Comment by squeek502** [comment]
Everything seems to be working correctly. The HO tooltips are chosen based on the ratio of saturation:hunger. The actual saturation restored doesn't matter, only how much it restores in proportion to its hunger (which is how saturation is defined in code, it is a modifier that gets multiplied by the hunger).

So, the HC Bacon Mushroom Burger has a saturation modifier of 0.6, while the rest of the HC burgers have a saturation modifier of 1.2 or 1.6 (HarvestCraft is incredible inconsistent and arbitrary with its saturation values). This means that it *is* unfulfilling, at least in comparison to other foods with the same hunger value. And small snack foods with more saturation than hunger *are* hearty, at least in comparison with snack foods that have a lower saturation:hunger ratio.

Also note that non-HO saturation values are *insanely high* in general, and that most high hunger foods easily surpass the max saturation its possible to achieve (10 saturation bars) and therefore will only show the 10 saturation.

I was correct about roasted pumpkin seeds: 2.4 saturation appears as 1 1/2 bars of saturation, so there's nothing weird going on there except the internal units being confusing (same thing with hunger, 2 hunger = 1/2 hunger bar).

I would assume in previous versions, you were either using `useHOFoodValues=true` (which would make saturation consistent) or some non-zero value of `foodHungerToSaturationDivider` (which would force saturation to be consistent across the board).
