### ISSUE TITLE
Health regen not working in modpack, possible conflict?

### ISSUE THREAD

**Issue by dizzysoul** [progwml6/HungerOverhaul#95]
I don't know if there's an incompatibility with another mod, but for some reason health regen (and a couple other health-related features) are not working properly in my modpack. Otherwise, everything runs just fine. I'm running forge 1291 in 1.7.10. 

[Here is a full log](https://dl.dropboxusercontent.com/u/17031956/latest.log), from startup to entering the world. I looked through my mod list and configs, and I don't see what could possibly be conflicting. My only guess is the HardcoreQuestingMod, which enables hardcore mode (though I did disable it for testing).

**Comment by squeek502** [comment]
Why did you close this?

**Comment by dizzysoul** [comment]
I re-downloaded the mod and it's dependencies, and deleted the configs, and restarted a new world, and it seemed to have went away. I think there's a gamerule that enables/disables regen that was getting triggered for some reason, and something I did managed to fix it.
